# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_right', models.BooleanField(default=False)),
                ('is_service', models.BooleanField(default=False)),
                ('text', models.TextField(verbose_name='Text')),
                ('user', models.CharField(max_length=250, verbose_name='User')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('question_ru', models.TextField(null=True, verbose_name='Question')),
                ('question_en', models.TextField(null=True, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('answer_ru', models.TextField(null=True, verbose_name='Answer')),
                ('answer_en', models.TextField(null=True, verbose_name='Answer')),
            ],
        ),
    ]
