# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='timer',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
