# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='answer_en',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='answer_ru',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='question_en',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='question_ru',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question', verbose_name='Question'),
        ),
    ]
