# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(verbose_name='\u0412\u044b\u0438\u0433\u0440\u0430\u043d\u043e')),
                ('lose', models.IntegerField(verbose_name='\u041f\u0440\u043e\u0438\u0433\u0440\u0430\u043d\u043e')),
                ('leave', models.IntegerField(verbose_name='\u041f\u043e\u043a\u0438\u043d\u0443\u0442\u043e')),
                ('all', models.IntegerField(verbose_name='\u0412\u0441\u0435\u0433\u043e')),
                ('coins', models.IntegerField(verbose_name='\u041c\u043e\u043d\u0435\u0442\u044b')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
        ),
    ]
