# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 14:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0, verbose_name='\u0412\u044b\u0438\u0433\u0440\u0430\u043d\u043e')),
                ('lose', models.IntegerField(default=0, verbose_name='\u041f\u0440\u043e\u0438\u0433\u0440\u0430\u043d\u043e')),
                ('leave', models.IntegerField(default=0, verbose_name='\u041f\u043e\u043a\u0438\u043d\u0443\u0442\u043e')),
                ('all', models.IntegerField(default=0, verbose_name='\u0412\u0441\u0435\u0433\u043e')),
                ('coins', models.IntegerField(default=0, verbose_name='\u041c\u043e\u043d\u0435\u0442\u044b')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440\u043a\u0430')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('rating', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('m', '\u041c\u0443\u0436\u0447\u0438\u043d\u0430'), ('f', '\u0416\u0435\u043d\u0449\u0438\u043d\u0430')], default='m', max_length=10, verbose_name='\u041f\u043e\u043b')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u041f\u043e\u043b')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
