# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180131_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430'),
        ),
    ]
