# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='all',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='coins',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='leave',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lose',
        ),
        migrations.AddField(
            model_name='profile',
            name='account',
            field=models.IntegerField(default=0, verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Is online?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wins',
            field=models.IntegerField(default=0, verbose_name='Wins'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ammount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ammount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
