# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='resolved',
            field=models.BooleanField(default=False, verbose_name='Satus'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.TextField(max_length=100, verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='page',
            name='alias',
            field=models.CharField(max_length=150, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.CharField(max_length=250, verbose_name='META description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_keywords',
            field=models.CharField(max_length=250, verbose_name='META keywords'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(max_length=150, verbose_name='META title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
