# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180216_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_en',
            field=models.CharField(max_length=250, null=True, verbose_name='META description'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='META description'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_keywords_en',
            field=models.CharField(max_length=250, null=True, verbose_name='META keywords'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_keywords_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='META keywords'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='META title'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='META title'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
    ]
