# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 15:05
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180226_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
